### ISSUE TITLE
Epic 12.14.2021

### ISSUE THREAD

**Issue by wrunion** [mapping-action-collective/healthy-transitions-frontend#18]
Priority, in order:

- [x] https://github.com/mapping-action-collective/healthy-transitions-frontend/issues/30
- [x] https://github.com/mapping-action-collective/healthy-transitions-frontend/issues/23
- [x] https://github.com/mapping-action-collective/healthy-transitions-frontend/issues/22

Minor, not urgent: 
- [x] https://github.com/mapping-action-collective/healthy-transitions-frontend/issues/20
- [ ] Display "Last Update: [date]" with the date of most recent CSV upload. 
- [ ] Display MAC & DS logos
- [ ] Display disclaimer in footer, with text to be provided 

Non-urgent, but crucial overall: 
- [x] Multiple page/routes that users can navigate to, including: "About," "Resources," and potentially more. 
- [x] https://github.com/mapping-action-collective/healthy-transitions-frontend/issues/21
